# Generated by Django 4.2.23 on 2025-06-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0002_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='services_offered',
            field=models.ManyToManyField(blank=True, related_name='providers', to='services.service'),
        ),
    ]
